### ISSUE TITLE
UUID not inserted in empty cell

### ISSUE THREAD

**Issue by Mauricevb** [TablePlus/uuid-generator#7]
Inserting an UUID doesn't work when you open a table, create a new cell and try to insert the UUID in a new cell. 

It does work however when you first fill in some text in the cell. Once you've done this, the UUID plugins keeps working until you open another table. The bug is easy to reproduce. I'm using 3.12.0 (latest version right now). 

![VID](https://user-images.githubusercontent.com/2742292/103688803-ae1eb680-4f92-11eb-9c2a-443875c7f044.gif)

**Comment by timrspratt** [comment]
I feel this is an important bug to sort out

**Comment by ChristopherDosin** [comment]
I have the same issue with 3.12.4 - Also within the pro version. Any idea @huyphams ?

**Comment by huyphams** [comment]
Hi please update the UUID plugin to version 1.1 it should fix the issue. (Press Command + L to update)
